name: Build

on: [push]

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Setup Xamarin / Mono
        uses: maxim-lobanov/setup-xamarin@v1.1
        with:
          mono-version: 6.6 # specify version in '<major>.<minor>' format
          xcode-version: 11.x # set the latest available Xcode 11
      - name: Android Build
        working-directory: Android
        run: ./gradlew build
      - name: iOS Build, Lint and Test
        run: pod lib lint --allow-warnings
      - name: Xamarin Build Fat Swift Framework
        run: xcodebuild -workspace iOS/MapsIndoorsUtils.xcworkspace -scheme MapsIndoorsUtilsFat
      - name: Xamarin Build Fat Obj-C Framework & Bindings
        run: xcodebuild -workspace iOS/MapsIndoorsUtils.xcworkspace -scheme MapsIndoorsUtilsXamarinIOSFat
      - name: Xamarin Build Solution
        run: msbuild Xamarin/MapsIndoorsUtils.sln
      
