name: Build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Build Android project"
        working-directory: Android
        uses: vgaidarji/android-github-actions-build@v1.0.1
        with:
          args: "cd Android && ./gradlew build"